apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: lindas.admin.ch
  app.kubernetes.io/name: trifid

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
